spring:
  devtools:
    remote:
      secret: Support1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://35.195.112.211:5432/postgres
    username: docker
    password: docker
    password2: '{cipher}AQCeyBNX/stQdc1IgEm77hOTw5hwTr6s9C2OCsY+ZTUhxjE/vrEbCmjqLZdiXIRjqF95f9YpU1N0h13GldDEENj1kxzRq/c7ARO3Xtf2CbpJkWgSVYBAvYsxueAtLffcw6u4sRdnixhWdG9EM0Jrk31fvdUcvLXM2gJC4tr58uC2VfmGGKqozuHTFhrnU5fQJEUMkgpFppr6M1/BEMqV43wKpQ/mke/wAWdVUoVzvNCm/O7t6/oSPZYVjEwJo0Bn1iGgQaEEFvJt5rg2OkAhOyHfcN9r53wAn631rESqnBjGjiTpJemz36i4R9oC5GbV9BIql9NTAVoaupS2teRvQrZWC8QnzNtVA95Cyw5wb9emWC4NGxbNr5hTN7NVo9gr9NM='

  data:
    elasticsearch:
      cluster-nodes: 35.205.27.133:9200  
b2b:
    jmsConfig: rabbitmq://35.205.158.134:5672/
    elasticsearch:
      host: 35.205.27.133
      port: 9200
      username: elastic
      password: elastic
