spring:
  devtools:
     remote:
        secret: Support1

b2b:
   jmsConfig: rabbitmq://35.205.158.134:5672/

test:
  '{cipher}AQBDg804WPVizcdMQ18oecBxpx7qxaaBN6QsDJU2SV2vYCqVMTn0qATTsrE63K1A6DAziplQEfJ2No7nop6tfUXmco5BpqdIDJ744Xzq81Y+54XXM5C8MV3EvElcs+jKORp7tN6SblT9BY3iHNu0E8x7cop9sBU0B/mmhMXFHAtK/u1J/GxMRmRdEeuwT+KHrlKqFtIssG5QLNjcCKAY9j6B8sBzQDGOcoTP+sMMZy5oY2dE6b7kd+P8usZ2Fu3ZL8s9IAGlUHxJjoIrs7zAITYBTwpgZlMpEyP4Re1JGdLwux6J051q+YT+oDefkRA/FGr5cGjiFXw4Km8lFYOq5k09xmfdWGlbvk7fGsTq1MWs/Bxr/zgkBOddE7HwXkH9Q1s='