spring:
  jpa:
     hibernate:
        ddl-auto: create
     properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
     driverClassName: org.postgresql.Driver
     url: jdbc:postgresql://127.0.0.1:5432/caml
     username: caml
     password: caml
b2b:
  routeconfig: file://%queueName%/
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    username: elastic
    password: elastic
